import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            ></a>
          </div>
        </div>

        <div className={styles.center}>
          <div style={{ backgroundColor: "#191970" }}>
            <Image src="/company.svg" width={200} height={200} />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="/map"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              First <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Here you will find a 3d node vizuliation of the different
              companies
            </p>
          </a>

          <a
            href="/api/runPy"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Secound <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Here you will find a streamlit MAP
            </p>
          </a>

          <a
            href="/api/runPyt"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Third <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Another streamlit map which is also 3d
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Fourth <span>-&gt;</span>
            </h2>
            <p className={inter.className}></p>
          </a>
        </div>
      </main>
    </>
  );
}
